### ISSUE TITLE
SemiAutoLogin

### ISSUE THREAD

**Issue by Murturtle** [EaglerRinth/eaglerrinth.github.io#10]
### Description

Press L to login without typing!

### Mod url

https://raw.githubusercontent.com/Murturtle/MursMods/main/SemiAutoLogin.js

### Mod source code

https://raw.githubusercontent.com/Murturtle/MursMods/main/SemiAutoLogin.js

### Mod Author

```bash
name: Murturtle
github: https://github.com/Murturtle
```

**Comment by radmanplays** [comment]
added
