### ISSUE TITLE
FreshEaglerUI

### ISSUE THREAD

**Issue by Murturtle** [EaglerRinth/eaglerrinth.github.io#11]
### Description

Makes the UIs slide in and re works the main screen!

### Mod url

https://raw.githubusercontent.com/Murturtle/MursMods/main/FreshEaglerUI.js

### Mod source code

https://raw.githubusercontent.com/Murturtle/MursMods/main/FreshEaglerUI.js

### Mod Author

```bash
name: Murturtle
github: https://github.com/Murturtle
```

**Comment by radmanplays** [comment]
added
