### ISSUE TITLE
[SUBMISSION] - Chat commands mod

### ISSUE THREAD

**Issue by AstralisLLC** [EaglerRinth/eaglerrinth.github.io#12]
### Description

An open source mod with a built in  customizable bug reports system!

### Mod url

https://raw.githubusercontent.com/AstralisLLC/EaglerForge-Mods/main/chat%20utils.js

### Mod source code

https://raw.githubusercontent.com/AstralisLLC/EaglerForge-Mods/main/chat%20utils.js

### Mod Author

```bash
name: NeverFlag [] Astralis
github: https://github.com/AstralisLLC
```

**Comment by radmanplays** [comment]
added
