### ISSUE TITLE
Just Enough Items Mod for Minecraft

### ISSUE THREAD

**Issue by JustLachin** [EaglerRinth/eaglerrinth.github.io#13]
### Description

This is just a suggestion and it's very important to add!
As you play through a [Minecraft world](https://apexminecrafthosting.com/uploading-a-world-to-your-minecraft-server/), recipes are crucial to create any block or tool that you’ll need to use. This is especially true when playing with mods, as learning new recipes can be confusing for unfamiliar players. While searching for crafting information online, it can become tedious, leading to a desire for an all-in-one recipe manager. Fortunately, Just Enough Items (JEI) is a Minecraft mod that displays information for vanilla and modded crafting recipes. In addition to this, you may review the usage of items among other information from the mod.

https://apexminecrafthosting.com/just-enough-items/

### Mod url

https://apexminecrafthosting.com/just-enough-items/

### Mod source code

https://apexminecrafthosting.com/just-enough-items/

### Mod Author

```bash
This is just a suggestion and it's very important to add!
https://apexminecrafthosting.com/just-enough-items/
```

**Comment by radmanplays** [comment]
this is for eaglerforge mods ONLY. not suggestions and minecraft forge mods

**Comment by JustLachin** [comment]
> this is for eaglerforge mods ONLY. not suggestions and minecraft forge mods

I know. So, do you have a chance to add this kind of mod (for EglerForge)?

**Comment by radmanplays** [comment]
its not possible to make in eaglerforge as of right now

**Comment by stpv221** [comment]
actually, someone did manage to make custom crafting recipes. could it be possible using ModAPI.mcinstance?

**Comment by stpv221** [comment]
random question: would it be possible to compile the client with minecraftforge?
