### ISSUE TITLE
[SUBMISSION] - <Keystrokes>

### ISSUE THREAD

**Issue by notsharingrealname** [EaglerRinth/eaglerrinth.github.io#14]
### Description

Its a Keystrokes mod ._.

### Mod icon

no icon sorry

### Mod url

https://raw.githubusercontent.com/notsharingrealname/keystrokes/main/Keystrokes.js

### Mod source code

https://github.com/notsharingrealname/keystrokes/blob/main/Keystrokes.js

### Mod Author

```bash
name: NotSharingName
github: https://github.com/notsharingrealname/keystrokes/blob/main/Keystrokes.js
```

**Comment by notsharingrealname** [comment]
or package com.example.eaglercraftmod;

import net.minecraft.client.Minecraft;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraftforge.client.event.RenderWorldLastEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod(modid = "eaglercraftmod", name = "Eaglercraft Hitbox Mod", version = "1.0")
public class EaglercraftMod {
    private static final String MOD_ID = "eaglercraftmod";
    private static final String MOD_NAME = "Eaglercraft Hitbox Mod";
    private static final String MOD_VERSION = "1.0";

    @Mod.EventHandler
    public void init(net.minecraftforge.fml.common.event.FMLInitializationEvent event) {
    }

    @SubscribeEvent
    public void onRenderWorldLast(RenderWorldLastEvent event) {
        EntityPlayer player = Minecraft.getInstance().player;
        if (player != null) {
            double playerPosX = player.posX;
            double playerPosY = player.posY;
            double playerPosZ = player.posZ;

            double hitboxWidth = 0.6;
            double hitboxHeight = 1.8;
            double hitboxDepth = 0.6;

            double hitboxX = playerPosX - hitboxWidth / 2;
            double hitboxY = playerPosY - hitboxHeight / 2;
            double hitboxZ = playerPosZ - hitboxDepth / 2;

            drawHitbox(hitboxX, hitboxY, hitboxZ, hitboxWidth, hitboxHeight, hitboxDepth);
        }
    }

    private void drawHitbox(double x, double y, double z, double width, double height, double depth) {
        // Add your hitbox rendering code here
    }
}

**Comment by egglercraftdev** [comment]
Hmm Looks nice! I am adding itt

**Comment by egglercraftdev** [comment]
BRUH THATS JAVA

**Comment by egglercraftdev** [comment]
LMAOOOOO

**Comment by egglercraftdev** [comment]
u must do with js
