### ISSUE TITLE
[SUBMISSION] - EaglerForge StatsHud

### ISSUE THREAD

**Issue by AstralisLLC** [EaglerRinth/eaglerrinth.github.io#2]
### Description

An all-new StatsHud, soon to be updated with customization functionality!

### Mod icon

https://media.discordapp.net/attachments/1110272979058831440/1221128671788535808/StatsHudLogo.png?ex=661173b2&is=65fefeb2&hm=73c20ec2c8a9b31947ad8c0f9e2b50cbd2b089da73af1bbc2e1f05b3791a33b4&=&format=webp&quality=lossless&width=402&height=402

### Mod url

https://raw.githubusercontent.com/AstralisLLC/EaglerForge-Mods/main/StatsHudv3.js

### Mod Author

```bash
name: NeverFlag
github: https://github.com/AstralisLLC
```

**Comment by egglercraftdev** [comment]
👍 Nice

**Comment by radmanplays** [comment]
added

**Comment by orphanlol** [comment]
ong ong
