### ISSUE TITLE
[SUBMISSION] - <replace this with the name of your mod>

### ISSUE THREAD

**Issue by GoldenPopeye261** [EaglerRinth/eaglerrinth.github.io#21]
### Description

rpg with classes custom structers weapons ores and more...

### Mod icon

Darkrpg

### Mod url

https://www.curseforge.com/minecraft/modpacks/darkrpg-forge

### Mod source code

Idk

### Mod Author

```bash
name: radmanplays
github: https://github.com/radmanplays
```

**Comment by radmanplays** [comment]
eaglerforge mods only!!!
