### ISSUE TITLE
Furnitiure mod

### ISSUE THREAD

**Issue by mikeyturtlemze** [EaglerRinth/eaglerrinth.github.io#22]
### Description

furnitures

### Mod icon

https://minecraft-forum.net/minecraft-mods-downloads/1-6-4-mrcrayfishs-furniture-mod-download-2-2-2-2/

### Mod url

https://minecraft-forum.net/minecraft-mods-downloads/1-6-4-mrcrayfishs-furniture-mod-download-2-2-2-2/

### Mod source code

https://minecraft-forum.net/minecraft-mods-downloads/1-6-4-mrcrayfishs-furniture-mod-download-2-2-2-2/

### Mod Author

```bash
name: radmanplays
github: https://github.com/radmanplays
```

**Comment by Project516** [comment]
This is for real Minecraft not eagler

**Comment by radmanplays** [comment]
no
