### ISSUE TITLE
[SUBMISSION] - OffhandModV2

### ISSUE THREAD

**Issue by MrNorshare** [EaglerRinth/eaglerrinth.github.io#25]
### Description

to get a offfhand on eaglercraft press "f" works on servers with /offhand command

### Mod url

data:text/javascript;base64,TW9kQVBJLnJlcXVpcmUoJ3BsYXllcicpOwp3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcigia2V5ZG93biIsIGV2ZW50ID0+IHsKICAgIGlmIChldmVudC5rZXlDb2RlID09ICc3MCcpIHsKICAgICAgICBpZiAoJy9vZmZoYW5kJy5jaGFyQXQoMCkgPT09ICIvIikgewogICAgICAgICAgICBNb2RBUEkucGxheWVyLnNlbmRDaGF0TWVzc2FnZSh7CiAgICAgICAgICAgICAgICBtZXNzYWdlOiAnL29mZmhhbmQnCiAgICAgICAgICAgIH0pCiAgICAgICAgfQogICAgfQp9KTsKCndpbmRvdy5hZGRFdmVudExpc3RlbmVyKCJrZXlkb3duIiwgZXZlbnQgPT4gewogICAgaWYgKGV2ZW50LmtleUNvZGUgPT0gJzcwJykgewogICAgICAgIE1vZEFQSS5kaXNwbGF5VG9DaGF0KHsKICAgICAgICAgICAgbXNnOiAnSXRlbSBJbiBPZmZoYW5kJwogICAgICAgIH0pOwogICAgfQp9KTs=

### Mod source code

ModAPI.require('player'); window.addEventListener("keydown", event => {     if (event.keyCode == '70') {         if ('/offhand'.charAt(0) === "/") {             ModAPI.player.sendChatMessage({                 message: '/offhand'             })         }     } });  window.addEventListener("keydown", event => {     if (event.keyCode == '70') {         ModAPI.displayToChat({             msg: 'Item In Offhand'         });     } });

### Mod Author

```bash
name: Mr. Norshare
github: https://github.com/MrNorshare
```

**Comment by PvPdevlX** [comment]
how to add it to my eaglercraft client?

**Comment by MrNorshare** [comment]
get it on the discord

**Comment by MrNorshare** [comment]
also "chicken nuggy"
