### ISSUE TITLE
[SUBMISSION] - <FlyMod>

### ISSUE THREAD

**Issue by Notchripoff** [EaglerRinth/eaglerrinth.github.io#35]
### Description

It's a mod when player press Key F they fly 

### Mod icon

any one you wan't

### Mod url

https://github.com/Notchripoff/EaglerForge-Mods/blob/main/Fly.js

### Mod Author

```bash
name: Notchripoff/JAckson
github: https://github.com/Notchripoff
```

**Comment by radmanplays** [comment]
this dosnt even use the modapi, stop using chatgpt
