### ISSUE TITLE
[SUBMISSION] - EaglerHomes

### ISSUE THREAD

**Issue by bImPatman** [EaglerRinth/eaglerrinth.github.io#36]
### Description

This is a Positioning system that lets you set homes and teleport to homes.

### Mod icon

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEBUQERIVFhUWGBgYFhgWGBoYEhUYFxYWFhgYFxYaHiggGhslGxgTIzEhKCkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQGi8iHyYxNTMwLTcrNzAtLS0wKzIrLS0tLS0tMy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0rLf/AABEIAOEA4AMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAAAQUGBwgEAwL/xABSEAABAwICBAQPDAgFBAMAAAABAAIDBBEFEgYTITEHQVGRFBYXIjI1U1RhcYGxstHSCBUjM3JzdJKTocHTNEJSg5SztMNiY4KiwiVVo/AkQ2T/xAAaAQEAAwEBAQAAAAAAAAAAAAAAAQMEAgUG/8QAKhEAAgIBBAMAAAQHAAAAAAAAAAECAxEEEiExE0FRFCKh8BVSYYHB0fH/2gAMAwEAAhEDEQA/ALwCVIEqAEIQgBCEIAQhCAEITbj+PUtBFr6qTVx5g3Nlc7rjews0E8RQHrieL0tKGmpnhhDrhplkbGHEb7ZiL8Sb+nLCv+40f8RF7SrLhMeNI4oWYOeiXU7i6a3wWQSCzNs2TNfI/de1tvEq/wCpFjveX/mp/wAxAaN6csK/7jR/xEXtJ5p52SMbJG5r2OAc1zSHNc0i4LXDYQRxrLPUix3vL/zU/wCYrlwLT7C8OpIKGrqRHUU8McU0eSRxZIxjWubmYwtdYg7QSEBYq8auqjhYZZXtjY3a573BrGjdcuOwL1abi4US4Wu0tZ82PTagI1wv4hDiOGmnw+WOqmEkb9XTPbNKGtuC7JGS7KCW7bW2hUd0o4v3hW/w83sqZ+517bSfRpP5kK0igMd9KOL94Vv8PN7KOlHFu8K3+Hm9lbEQgIXofpFQ0uH0tPU1dPDNHBE2SKWaOOWNwjbdr2OcHNcOQi6mYIO0LI/Cl25rfnj5gtaU3YN+SPMgPVCEIAQhCAEIQgECVIEqAEIQgBCEIAQhCAFWfug+0/7+PzPVmKM8IWifvtR9Ca7U/CNfmyZ+xDhbLmby778SAq/3NLwDX+Kn/vq8dePCqWFI3Q1hkc41nRZa2wGo1epDjfe/NfWeC2XjuvPq9xd4P+3H5aAu3XjwrJHCYf8ArFb8+/zqyur3F3g/7cflr0m4I/fc++nRup6LDZ9Vqc+r1rQ/Jn1jc1r2vYeJAXXD2LfEPMopwtdpaz5sem1SyNtgByCyatLcE6PopqPWavWty58ubL1wN8txfdyoCg/c8Otish//ADSfzIVo7Xjwqlo9ExomHYoZjVgjUasM1JGsc12bPmfuybrce9efV7i7wf8Abj8tAXbrx4Ua8eFUn1e4u8H/AG4/LR1e4u8H/bj8tAVtwon/AKzW/PHzBa1puwb8keZUvUcEvvyffXozU9Fhs+q1Os1esaDlz6xua3LYeJXXEzK0DkAHMgPpCEIAQhCAEIQgECVIEqAEIQgBCEIAWfKjh4xBr3N6GpthI3ScRt+2ufTLhVxemxCqp4p2iOOaRjAYoyQ1riALlu3YrSPBJgbuuNHcnafhp952n/7EBEdAeF6sxHEYKOSCBjJM+ZzM+YZYnvFruI3tCudVjpTobh+DUc2JYfBqqmBt4nl8kgaXERu6yR5abtc4bRxpm4G9P8RxLEHwVUrXxtge8ARsb1wkiaDdovuc7nQFgac6D02MNiZUPlYIi4t1RaCS4AG+ZruRRDqC4X3es+vF+UrWQgKp6guF93rPrxflKysHw5lLTxUzC4shjZG0usXFrGhoLiABew5AuxCAEIQgGPTHReDFKboWd0jWZmvvGWh923ttc1wtt5FBeoLhfd6z68X5StZCAqnqC4X3es+vF+UjqC4X3es+vF+UrWQgOPBsNZS08VNGXFkTGxtLrFxDAGgkgAXsORdiEIAQhCAEIQgBCEIBAlSBKgBCEIAQuKtxamgcGzTxRuIuA+RrCRuuA4jZsPMvDpkoO/Kb7aP2kBlPhF7b130iX0ytaNLrDfuXL0xYf33TfbR+0sgVlbLrH2kfbM61nG1rndtQGneFkn3lrL37Bv8ANYqn9zn21l+iyfzYE0cDNTI7HKQOe4i8uwkkfo8vEVqYNHIgFQhcdbi1NAQ2aeKMkXAkkawkbrgOI2IDsQsz8Mcs02LSSUrnyRFkdnQkujJDADZzNl7qEaiu/ZqeaRRuX062S+Gz0LImirKttfSukEzWNqIS8vzhgaJWlxcTsAAvclarpsco5XiOOpge87mtlY5xsL7ADc7AeZE0+iGmuxwQhCkgEIQgBCEIAQhCAEIQgBCEIBAlSBKgBNGkOk9Fh4YauYRCS4ZcOObLa/Yg8oTuqV90v8VRfLm9GNAR3hjqWYvVQz4e4Txsi1bnDrQH53Oy9fY7nNPlUA6WK3uP+5ntKRaCzBtO8Huh9FikfRTfCsFuqlCbikj1aNBCytSbfJXXSvW9x/3M9pHSxW9x/wBzPaVi9FN8KOim+FV/jZ/EXfwyv6/3/YYODakfh+KQVlWNVBFrM7yQQ3NDIxuxpJ2uc0buNaGwHTTDq+Uw0tS2WQNLy0NeLNBaCbuaBvc3nVC6TVDTSSjbuHpNTbwRaVU2F1z6ipz5HQOjGRuZ2YyROGwkbLNctmntdkcs87V0KmaivhpTSHSaiw8MdVzCIPJDCQ43LbE9iDyhUZwx1UeL1MM2HuE8bIyx7h1oDs5dbr7HcRzrr4S9JKfSCOFlDmBgc5z9cMgs8ANy2zX7Epj0coXUcTo5SCS4uGXaLWaOMDkKi69QXHZOm0rtksp4+nro5E6CmZHKMrxmuN9ruJG0bNxC9ZsfpWOLXTAEGxFnbDzJuxTH4YpSx2a9huFxtHjQODWtrLVUT4AyYCRgc54cGvAcMwDCAbEcZWWqh2ycprGTfqNTHTwUYNNrgeKuUPje1puXNcAOUlpATHwcUcmH4nT1lWNVBEXl7yQQ0OiewbGknsnNG7jSR6QQawR9fmzBu4Wve2+/KnbFmGeB8LNjniwzbBvB22vyLmqc6XhrGTu+qvUR3ReWl6LxwHTXDq6Uw0tS2WQNLy0NeOtBAJu5oG9w51IFmvg4lbgVW+trDeMxOi+Cu5+Zz2OGw22WYePkV2aGad0eLGUUok+CDC7WNDezzWtYm/YlelGSkso8ScJQeJLBKEIQujkEIQgBCEIAQhCAEIQgECVIEqAFCOE3QI4y2BoqBDqS8/F582cNH7TbWy/epuhAZk0rwcaPSMpXSdEaxutzBurtclmW13X7C978akOi+AmupI6oSBgfm60tzEZXuZvuP2b7uNcXuke2FP8AR/7sin3A3hbJMEpnlzgTrt1rbJ5RyKiWmrk8tGmOtvhFRg+v6IY+kd3fA+zPtLwr9EHRRSS68HIxz7ZLXytLrXzbNytj3kj/AGnfd6k26TYOxtFUuzO2QTHi7m7wKPwlPz9WP4hqv5v0X+jMuJaSNmidGIyMw33BttB5E34DhXRUpjz5bNLr2vuIFrXHKvPAqJs9QyJxIDr3I37Gk8fiU5w7AYqNxljc8kjLZxFrEg8QHIFxOUKIuMeGX1Qt1U1OfKXHw+cDwfoLP1+fPbiy2y38Jv2X3Lxx7HmwPaDGTdt9h8J8CNJMafA1hDWm5I234rJx0R0XgxqB1TUOkjcyQxgRFobYNY+5zNJvdx5gqKqpXS3z5Rq1GohpoeOvhr/p54XoCcWhbXCo1QkuAwx5yMjizss4vfLfdxq7NHdGjDSQRa0HVxRtvltfK0C9r7NyryOtOEgUEAD449rXSbXnOdYb5bDe48Sc4eEuqa0NEMNgAP1+L/UvVjXhJI8Gdu+TciIVvBUYS+p6LB1ZdLl1Vr5bvy3z7N1r2UcwrSZsszWCMi99ubkBPJ4FYR0plqDqHMYGy/BuLc2YCTrCRc2vYlMuOcHtJh1PJWxSTOfC3M1ryzIbkN22YDuJ41RqNOprlc+jTpNZKt4zw3zwN2L0nRcWpvk2h17Zt3FbZyrp0Nx5mjete9jqjojIBlIjyavOdt73vn+5R7R/SB80paWNFmk7L8oHL4U74lhrKwBshc0MNxlttvs23B5FgrsnTJQl0evdVXqYOytcl28HumTMYp31DITEGSGOznBxNmMde4A/a+5SlZxwrTWXR2PoWmiZK2VxlJlJzB1mssMthazR96urg90ikxLD4qyRjWOeZAWsvlGSRzBv27mr0YyUllHjTg4ScX2SRCELo4BCEIAQhCAEIQgECVIEqAEIQgM8e6R7YU/0f+7IrN4Ee0VL++/qJVWXuke2FP8AR/7sil3BLUyNwenDXOA+F2A7Pj5EIbwWyszycK2LTymlkkjMcjzE8atoJY85HC43GxO1celuneKxV9TFHWzNYyaRrWh2wAOIACeDhkA68Qxhw2h2UZr773tvuqbrlWufZr0undz4fRyw4DTQOEsbLPbuOZxtfYdhNtxK5NJMSligztIvmA2gHeCvvHal7aaRwcQQBY3/AMQXxwVWrK18VUBMwQucGyAOaHB8YDrHZexO3wlYqKpWtSk8pHpaq+Gni64rDazwOHBjhcGL9ECuZrBDq9XZzmWz6zN2BF+xbv5FKMVibhDm09CNXG8axwN33eSWE3fcjY1uzwKf6IYLSQmXU08UeYMvkY1t7ZrXsNu886h/CzGG1cQAA+BG75b16tUUnhHz905T/M2NsELaponmGZ7thI60daco2DZuATBWsDZHtG4OIHkKI6yRoyte4DkBsF5OcSSSbk7STxrU2sGVJ5JMcNijGsa05mjM03Owt64bL8oC8aTEpa54pKkh8Mtw9oAaSAC7sm2I2gbkymvlIsZHW3b076CMDsRpwRcFzth3fFPUTw0TBNM4dO9GaPDKM1NHFkkztZcve8ZXXuLOJHEFFNFsXmmMmcjZltYAb83qWjdJ8JppYMkkMb25gbOaC24B4iqX4W6OGihgdSRsgL3uDjE1rC4BoIBsNtrnnXnXUqyLx39PU0uplTNJttfDiqMLhqrOmbmLdg2kWG/iK8JtP6/CbUNG9jIWC7WuYHkF5L3dc7adpK4NE6yWSFxe9xOe208WVqffe+GXr5ImOdyuaCdm7aVhha6ZuMnnB61tEdTWpwSTZe2iFfJU4fS1EpBfLDG95AsC5zATYDdtKd1k7FNNcTppX08FZLHFGcjGNdZrGgABrRxABatpzdjSeQeZemnlZPElHa2j0QhCk5BCEIAQhCAQJUgSoAQhNWO6R0dCGGrnZEH3yZr9dlte1h4RzoCjfdI9sKf6P/dkVZ0oq8g1WvybbZM+XfttbZvurJ4Z5mYrVwzUDmzxshyOcwgAOzudl6622xafKuPRyMw0zIpBleM1xvtd7iN2zcQqLr1WuOWa9NpXbLDyl9wdWFfERZ+yyNzZuyvlF7323uuCqma5jmtcC4tcGhpu4uIIAAG0km1gvmpxena9wdK0EE3G2+/xLl0e0CxRldTyOpXBrZ4nE549jRI0k7Hcix1UO2TcuD0dRqo0RUY4frs+uDbCK1uKU5lp6gMBkuXxvDR8DJa9xbfZaFwOmLZSSy3Wne23GF9YfRStla5zSAL3OzkPhT8vU6PA5k8sQAKr+FWhmkq4jHFI8CIAljHOAOd+y4G9WihTGWHkmUcrBSuFgRxBkoyPF7teMrxcki7XbRsUfxAgyyW3Zja27eptp1ozW1FdJLDA57CGWcCwA2YAd7gd6YOkvEu9XfWj9paN6aMvjabO+V7HMLWlpJaQACCSSLAADebrz0Gw2oZiNO58ErWhzrl0bw0fBvG0kWCMI0QxBlRC91M4NbLG5xzM2Br2knsuQFXQubLPR1VV7EITRj8GYMs2+07hfkTwhZzS1kzvwzYXVPqINRBM4CM31cbyOzO/KEx4KHQwNZPeOQXu2TrXi7ja4dt3LRmM0sj3gtaSLeDlKovhR0MxGoxF0kNOXNyRi+Zg2hu3YXXVV1Ktjgv0updE84ye8DmFoN2nYORRDAJa0YjTl7pxGKmIuLi/VhglbcknZlt5LJxjqo6Zop53hksYDXtO9rgBcXGxPdRIHRuANyWkDwkiwWCuyVMmmj2LqYamKal1857L8hxame4MZPE5x3BsjS48ewA7V2LLHBxQyUOKU9VVN1UMZeXvcRlaDG9ovYk7yB5VovBtMMOrZNTTVMcr8pdlbe+UEAnd4Rzr01JPpnhyhKPElgfEIQpOQQhCAQJUgSoBm0r0mpsMgFRUlwYXhnWtzHM4OI2cnWlUzwn6QU+PsgbQON4HPMmtaWD4QNDbb79g5TD3Q3ahv0iP0JVQ+jOONpNZmYXZ8u4gWy5uXxrixyUXt7LaVBzW/olmjdE6kidHLYkvLhl2ixDRx25CvHE8egjlLHF1xbi5QE3z6YxuN9U/nCesN0AOKxNr21AiElwGGPMRkcY9rg4Xvlvu41ihp5WTbsR6dmsrpqSpeX/g4uptXVY6KjdAGTASMzPcHZXjM24ybDYhaFpsJla5pOXYWk7eQjwLjwDRl0VJBFrQckUbL5bXysAva/gTOeFKMbOhn7P8Y9S9GMeMI8ScsvMiw0Ku+qnH3q/649SOqnH3q/649S62SHkj9LEQq76qcfer/rj1I6qcfer/AK49SbJDyR+liIVedVOPvV/1x6lOMJrRUQRTgZRIxrwDtIzAG1/KuXFrslST6OtCFwY7iQpaeSoLS4MAOUGxNyBv8qg6O9Crvqpx96v+uPUjqpx96v8Arj1LrZI48kfpYiZ8Rw2SSQubaxtvPg8SifVTj71f9cepHVTj71f9cepTskQ5xfsrjS/gxr6ivqJmOgDXyEi73X5NtmJlZjsDZBES7MHZN2y4OXf41oOgpTVRsqQcolaJA0i5bmF7X41TFdwVPjkkqei2nK50uXVnblJflvn8FrrPdSrFz6NWm1U6Xx0zwxZuvgfEzsniwvsG8HaV58Gz24JWOra1w1RidH8Hd7sznMI2WGzrSmCPS+MEHVO5wubH9JmVMOqbG5puDckW2LLp43QeMcHoauemsW5S5xx+8GltD9OaLFTI2lLyYg0vzsy9nmtbl7EqTKiPcz/GV3yYPPKr3W88kEIQgECVIEqAj+m2ikOLUwpZnvY0PbJePLmu0OAHXAi3XHmUE6geHd81XPH7CttCAypwr6GwYRUxQQSSPa+LOTJluDnc2wygbLAK4eBvCmyYLTPLiCddutbZPKFAvdI9sKf6P/dkVm8CPaKl/ff1EqENZJvDHlaGjiAHMs6Wu+3K633rRyzk34z/AFf8ldV7KbvR19AN5T9yOgG8p+5e9S8taSP/AHauekqHOdYnZbk8IV5QL0A3lP3I6Abyn7l91szm2tx3/BLRylzSTy/gEBwVEeVxaPAr20Q7X0vzEXoBUZXfGHyeZXnoh2vpfmIvQCpt6Lqex3Ue0/7W1HyW+m1SFR/T/tbUfJb6bVTHtF8umUzhdIJX5CSNhOzfsI9a9sWw5sIaWkm999uK3IuSlqXROzM32tuuvurrpJbB5BtusLb1r4wYucnVhWGNmaXOcRY22W5AeNcuJUwikLASQLb9+0XRS18kQIYRYm+0X8C8qmd0js7t5t4NycYHOS9dD+19L8zH6IXLjmDMFNO7M74qQ8X7Dl1aH9r6X5mP0QunH/0Sf5mT0HLI+zYllIyVoHgceIYjBRyuc1kpcCWWzjLG5+y4I3tHErp6geHd81XPH7Cqvgb7eUfypP5Mi1eoOiH6BcH1Ng7pXQSyv1wYHazLsyZrWytH7RUwQhACEIQCBKkCVACEIQGePdI9sKf6P/dkVm8CPaKl/ff1EqrL3SPbCn+j/wB2RWbwI9oqX99/USoCdLOTezHyv+S0as5sHwg+V/yV1Xspu9HfWfFu8nnC5MP7PyfiF3V0ThG4lpG7iPKFw4f2fk/EK72Zz1xL9Xy/gvrDuxPj/AL5xLc3y/gvrDuxPj/AJ7Ho5q74w+TzK89EO19L8xF6AVGV3xh8nmV56Idr6X5iL0AqrS6nsd1H9P8AtbUfJb6bU/ucACSbAbSTuAUW06xCB2HTtbLGSWtsA9pJ69vFdUx7RfLplUYHC18tnAEZSbHxhdOP0zGBmVobcm9h4kyiS2428RQ6W+91/GVrzxgxY5yPuAUrHscXMBOa20eALgxmJrJi1oAFhsG7cuITW3Ot4ikMgPH96Z4wMcl9aH9r6X5mP0QunH/0Sf5qT0HJs0SxKBtBTB00YIhZcF7QR1o3i6c8eP8A8Sf5mT0HLI+zbHoy/wADfbyj+VJ/JkWr1lDgb7eUfypP5Mi1eoJBCEIAQhCAQJUgSoAQmfSnSWmw2AVFU5wjLwy7WlxzEEjYPklRPq04L3WX7JyArz3SPbCn+j/3ZFZvAj2ipf339RKqX4ZtKqTE6uGalc5zWQ5HZmlpzZ3u3HwEK6OBHtFS/vv6iVATpZ3oj8Oz5xvphaIWdYHWlaeR4PM5W1+ym30TPSKVppZBfiHpNUOw7s/J+IT5i9Yx0L2i9zbi/wAQTHh3Z+Q+cLupNLkrsab4PXEv1fL+C+sO7E+P8AvnEv1fL+C+sO7E+P8AAKz2V+jmrvjD5PMrz0Q7X0vzEXoBUZXfGHyeZXnoh2vpfmIvQCqtLqez30h/RKj5mX0HLMrXt5QtP4vTulp5om2zPje0X3Xc0gX8pVIjgmxT/I+0PsriDSLJxbIfrG8qXWDlUv6k2Kf5H2h9lHUmxT/I+0PsqzeivYyH6xvKjWDlUw6k2Kf5H2h9lHUmxT/I+0PspvQ2MhsjmkHduKvbEtOcLNHIwVkJcYXtAvtvqyLbuVUPi1K6lmkp5bZ4nFrsu1txyHjXVPonVBjnfB2yk9lxWvyKm2xcHUXtGrgtr4abF6aad7Y42Ofmc42a28TwLnxkDyrSHVEwfv8Ag+sssUGBTTSNiZlzO3XNhuJ27PAnrqd13LF9c+yq3OK7ZZuRqDBNJKKtLhS1EcpZYuyG+XNe1/HY8ydVQPBnWRaPGeTEXgNnEbY9WHP2szl17DZ2QVx6KaVUuJxOmpXOcxjshLmlpzWDtx8BClNPolPI9oQhSSIE1aVY4zD6OWsexz2xAEtbbMbua3ZfZ+sujGq009LNOAHGKKSQA7ASxhcAT4bKjZ+FGTG2nC5KZsTKgWL2PLnNyfC7ARbbkt5VDeFkHVpPptBpJB0BDHJA5rhMXyZXNsy7Mtmm97vHMoj1M398t+ofaUgwTRWKgkM0b3uJaWWda1iQ6+wb+tCe+jDyBZp3PP5SiVjzwVRjuirqWRsZlDrtzXDbcZFt/gVmaA8JcOG4fDRPp5Xuj1l3NLQ055XyCwJvucB5F4YngTKxwke9zS0ZbNta1yb7fGuPpJh7rJzN9S6V3HJPkL6wXEBVU0NS1paJo2SAHeA9ocAbce1Z/b2f+r8U+0/CpPQMbRMpY3tpmiFrnSODnCIBgcQG2BICYYjd4PhHnW2l5yc2vOBxrewPk84XJh/Z+Q+cLrrOwPk84XJh/Z+Q+cLR7KUeuJfq+X8F9Yd2J8f4BfOJfq+X8F9Yd2J8f4BR7Ho5q74w+TzK89EO19L8xF6AVGV3xh8nmV56Idr6X5iL0AqrS6nsd0IQqDQCEIQAoJpbwmQ4dVOpX08ry1rXZmlob1wvxm68+EbT+XC54oo4GSB7C8lzi0izi22wFQCvpxjL/fCW8TnjKWMIc0aslgNyL7bLic1FHEpYOXF8COIzSVrJAxtQdYGObdzQ4DYSDYlPk8wdG5lt7S2/jFrr5pTqWNhG0MAaCd5sLXK+FklNtlDeSP4Ro+6CdkpkBDSTYAgm7SN9/CpX0YORcaVcuTfZDeRv0owQ4ixjGvEeQl1yM17i3EQujRXSqHRmF1LMx85meZQ6OzQBlayxDjv62/lXZDLl4k2Y5o3FiDmvke9hYC0BtrG5vtuFbXZt4fR3CeOGXLodpGzE6NlZGxzGvLgGutmGRxab22bwntUBTcIr8AjbhsVO2ZjAXh73lrjrHOeQQG22ElXZoziZq6OCqc0NM0TJC0G4bmaDYHjWpPKyaE8nlpf2uq/o0/8AKespaCuIxCEj/H/KetgVEDJGOje0OY9pa5p3Oa4WIPgIJVdcI+i1BRYXU1VLSwwzRtaWSMYA9t5GNNj4QSPKkllNEPlEbkmLhYr4VS9NFb3d3M31I6aK3u7uZvqWX8PL6U+JluxzObsC++ineBU/00Vvd3czfUjpore7u5m+pT4JfR4mPGNG9RMf8b/SKkkHZN8Y86rWXEJXOLnPJJJJOzaTvXQMdqhtErvu9S11PZ2S62y2ZGBwsdy84qdrTcKr+mat7u7mHqR0zVvd3cw9Sv8AMjjwv6WlNCH2vxIiiDRYKremet7u7mb6kdM9b3d3M31J5kPCywq74w+TzK1tHMTlbR07QRYRRgbORoWY34/VE3Mzr+T1Lvh05xNjQxtU8NaAALN2AbANy4nNM7jW17NPe+83KOZHvvNyjmWZen7Fe+38zfZSdP2K99v5m+yq8o72y+mm/feblHMj33m5RzLMvT9ivfb+Zvso6fsV77fzN9lMobZfSwOGapdJVQF1tkR3fLKieH6RVEEYijLcova7bnaSTt8ZUZxPSKrqXB08znlosCbbBe9tgXH0bJ+0VxKOSNhcVBUOliZI62ZzQ422C5FzsXuqji0jrGNDWzOAAsBs2AeRffTRW93dzN9SzuhnPiZbKVVL00Vvd3czfUjpore7u5m+pPBL6R4mW0vuOYt2BVF00Vvd3czfUjpore7u5m+pR4JfR4md/CI8urST+wz8Vprg67UUP0eL0AsjV1bJO/PK4udYC55Bu3LXPB12oofo8XoBaYrCSLksLBwlNOlH6JL4m+m1KhdEldoSoQCIQhABQlQgBIhCAEqEIBEJUIBEIQgBCEIAQhCAEIQgBKhCARBSoQCKysC/RofkN8yVCA//2Q==

### Mod url

https://github.com/bImPatman/EaglerHomes-for-EaglerForge/

### Mod source code

ModAPI.require("player"); ModAPI.addEventListener("sendchatmessage", function (event) {     if(event.message === "{sethome}"){         localStorage.setItem("HomePosX", Math.round(ModAPI.player.x));         localStorage.setItem("HomePosY", Math.round(ModAPI.player.y));         localStorage.setItem("HomePosZ", Math.round(ModAPI.player.z));         if (Boolean((Math.round(ModAPI.player.x) == localStorage.getItem("HomePosX"))) && Boolean((Math.round(ModAPI.player.y) == localStorage.getItem("HomePosY"))) && Boolean((Math.round(ModAPI.player.z) == localStorage.getItem("HomePosZ")))){             ModAPI.displayToChat({msg: "Home Set!"});         }else{             ModAPI.displayToChat({msg: "Failed to Set Home!"});         }     }else if(event.message === "{home}"){         ModAPI.player.sendChatMessage({message: "/tp " + localStorage.getItem("HomePosX") + " " + localStorage.getItem("HomePosY") + " " + localStorage.getItem("HomePosZ")});     }else if(event.message === "/help"){         ModAPI.displayToChat({msg: "{EGHomesHelp}"});     }else if(event.message === "{EGHomesHelp}"){         ModAPI.displayToChat({msg: "{sethome}"});         ModAPI.displayToChat({msg: "{home}"});     } });

### Mod Author

```bash
name: Patrick
github: https://github.com/bImPatman/
```

**Comment by radmanplays** [comment]
added!
