### ISSUE TITLE
VoxelMap

### ISSUE THREAD

**Issue by Madowgaming5** [EaglerRinth/eaglerrinth.github.io#4]
### Description

VoxelMap is a minimap and worldmap mod that makes a great effort to be accurate to the colors you see in the world (and your resource pack).   Display your surroundings, or view the entire (explored) world.

### Mod url

https://legacy.curseforge.com/minecraft/mc-mods/voxelmap

### Mod Author

```bash
name: radmanplays
github: https://github.com/radmanplays
```

**Comment by egglercraftdev** [comment]
Bruh thats not EaglerForge Mod 💀
