### ISSUE TITLE
Keystrokes Mod

### ISSUE THREAD

**Issue by ghost** [EaglerRinth/eaglerrinth.github.io#5]
### Description

Hello, I've made a simple keystrokes mod for EaglerForge/EaglerRinth. There will be much added to the keystrokes mod such as customization and more soon. If you do end up publishing this please do **NOT** set the name to _Keystrokes-For-EaglerForge_ set it to Simple Keystrokes or Keystrokes Mod (your choice).

### Mod icon

https://raw.githubusercontent.com/Hypverr/Keystrokes-For-EaglerForge/main/images/icon.png

### Mod url

https://raw.githubusercontent.com/Hypverr/Keystrokes-For-EaglerForge/main/out/keystrokes-mod.js

### Mod source code

https://github.com/Hypverr/Keystrokes-For-EaglerForge/tree/main

### Mod Author

```bash
name: Hypverr
github: https://github.com/hypverr
```

**Comment by egglercraftdev** [comment]
Good✅
