### ISSUE TITLE
Burmod [WIP]

### ISSUE THREAD

**Issue by Murturtle** [EaglerRinth/eaglerrinth.github.io#8]
### Description

A work in progress cheat client

### Mod url

https://raw.githubusercontent.com/radmanplays/Burmod/main/burmod.js

### Mod source code

https://github.com/Murturtle/burmod

### Mod Author

```bash
name: Murturtle
github: https://github.com/Murturtle
```

**Comment by Murturtle** [comment]
delete the old one upload this one

**Comment by orphanlol** [comment]
ok!

**Comment by orphanlol** [comment]
the one here? https://[raw.githubusercontent.com/Murturtle/Burmod/main/burmod.js](https://raw.githubusercontent.com/Murturtle/Burmod/main/burmod.js)

**Comment by radmanplays** [comment]
updated
