### ISSUE TITLE
Blur

### ISSUE THREAD

**Issue by Murturtle** [EaglerRinth/eaglerrinth.github.io#9]
### Description

Makes your fps 5 when unfocused!

### Mod icon

https://raw.githubusercontent.com/Murturtle/MursMods/main/Blur.png

### Mod url

https://raw.githubusercontent.com/Murturtle/MursMods/main/Blur.js

### Mod source code

https://raw.githubusercontent.com/Murturtle/MursMods/main/Blur.js

### Mod Author

```bash
name: Murturtle
github: https://github.com/Murturtle
```

**Comment by radmanplays** [comment]
added
